# https://github.com/gohugoio/hugoThemes#themetoml
name = "Jim Schubert's Resume Template"
license = "Apache-2.0"
licenselink = "https://github.com/jimschubert/jimschubert-resume/master/LICENSE"
description = "A modern single-column portfolio resume theme for Hugo."
homepage = "https://github.com/jimschubert/jimschubert-resume"
tags = ["portfolio", "resume", "minimal", "single-column"]
features = ["portfolio", "resume", "theme", "responsive"]
min_version = "0.161.1"

[author]
name = "Jim Schubert"
homepage = "https://github.com/jimschubert"